[package]
name = "bugstalker"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Derevtsov Konstantin <godzie@yandex.ru>"]

[dependencies]
nix = "0.25.0"
once_cell = "1.13.1"
anyhow = "1.0"
rustyline = "10.0.0"
gimli = "0.26.2"
object = "0.29.0"
memmap2 = "0.5.7"
ouroboros = "0.15.4"
typed-arena = "2.0.1"
fallible-iterator = "0.2.0"
itertools = "0.10.3"
unwind = { version = "0.4.1", features = ["ptrace"] }
rustc-demangle = "0.1.21"
thiserror = "1.0.37"
bytes = "1.2.1"
log = "0.4.17"
env_logger = "0.9.3"
tui = "0.19"
tui-textarea = "*"
crossterm = "0.25"
clap =  { version = "4.0", features = ["derive"] }
uuid = {version = "1.2.2", features = ["v4", "fast-rng", "macro-diagnostics"]}
os_pipe = "1.1.2"

[dev-dependencies]
assert_cmd = "2.0.4"
rexpect = "0.4.0"

[[bin]]
name = "hello_world"
test = false

[[bin]]
name = "calc"
test = false

[[bin]]
name = "vars"
test = false

[[bin]]
name = "mt"
test = false
