[package]
name = "bugstalker"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Derevtsov Konstantin <godzie@yandex.ru>"]

[dependencies]
nix = {version = "0.27.1", features = ["process", "signal", "uio", "personality", "ptrace"]}
once_cell = "1.13.1"
anyhow = "1.0"
rustyline = "12.0.0"
rustyline-derive = "0.9.0"
gimli = "0.28.0"
object = "0.32.1"
memmap2 = "0.9.0"
ouroboros = "0.18.0"
typed-arena = "2.0.1"
fallible-iterator = "0.3.0"
itertools = "0.11.0"
unwind = { version = "0.4.1", features = ["ptrace"], optional = true }
rustc-demangle = "0.1.21"
thiserror = "1.0.37"
bytes = "1.2.1"
log = "0.4.17"
env_logger = "0.10.0"
crossterm = "0.27.0"
clap =  { version = "4.0", features = ["derive"] }
uuid = {version = "1.2.2", features = ["v4", "fast-rng", "macro-diagnostics"]}
os_pipe = "1.1.2"
proc-maps = "0.3.0"
thread_db = "0.1.4"
smallvec = "1.10.0"
rand = "0.8.5"
ctrlc = "3.2.5"
strum = "0.25.0"
strum_macros = "0.25.2"
signal-hook = "0.3.15"
rayon = "1.7.0"
trie-rs = "0.1.1"
regex = "1.8.4"
walkdir = "2.3.3"
timeout-readwrite = "0.3.3"
tuirealm = {version = "1.9.1", default-features = false, features = ["ratatui", "derive", "crossterm"]}
tui-realm-stdlib = { version = "^1.3.0", default-features = false, features = [ "ratatui", "crossterm" ] }
syntect = "5.1.0"
unicode-width = "0.1.11"
tui-realm-treeview = "^1.1.0"
capstone = "0.11.0"
lru = "0.12.1"
chrono = "0.4.31"
sysinfo = "0.30.0"
indexmap = "2.1.0"
chumsky = {version = "1.0.0-alpha.6", features = ["default", "label"]}

[dev-dependencies]
serial_test = "2.0.0"

[features]
default = ["libunwind"]
libunwind = ["unwind"]
int_test = []

[[bin]]
name = "hello_world"
test = false

[[bin]]
name = "calc"
test = false

[[bin]]
name = "vars"
test = false

[[bin]]
name = "mt"
test = false

[[bin]]
name = "recursion"
test = false

[[bin]]
name = "signals"
test = false

[[bin]]
name = "sleeper"
test = false

[[bin]]
name = "fizzbuzz"
test = false
