[package]
name = "vars"
version = "0.0.0"
edition = "2021"
workspace = "./.."
publish = false

[[bin]]
name = "vars"
path = "src/vars.rs"

[dependencies]
uuid = { version = "1.8.0", features = ["v4", "v7"] }
