[package]
name = "tokioticker"
version = "0.0.0"
edition = "2021"
workspace = "./.."
publish = false

[dependencies]
tokio = {version = "1.35.1", features = ["time", "default", "rt-multi-thread", "macros"]}
rand = "0.8"
log = "0.4.20"
